version: '3.7'

services:
  # development environment for NOTICE
  notice:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    image: notice:dev
    container_name: notice
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - .:/app